const ENV = {
  dev: {apiUrl: 'http://10.0.2.2:3000/api/v1'},
  staging: {apiUrl: 'https://api-staging.airixai.com/api/v1'},
  prod: {apiUrl: 'https://api.airixai.com/api/v1'},
};

const __DEV__ = process.env.NODE_ENV !== 'production';
export const API_URL = __DEV__ ? ENV.dev.apiUrl : ENV.prod.apiUrl;

export const ENDPOINTS = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_FIREBASE: '/auth/firebase',
  AUTH_REFRESH: '/auth/refresh',
  AUTH_ME: '/auth/me',
  USERS_PROFILE: '/users/profile',
  USERS_STUDENT_PROFILE: '/users/student-profile',
  AI_DOUBT_SOLVE: '/ai/doubt/solve',
  AI_MENTOR_CHAT: '/ai/mentor/chat',
  AI_RANK_PREDICT: '/ai/rank/predict',
  AI_FLASHCARDS: '/ai/flashcards/generate',
  AI_STUDY_PLAN_TODAY: '/ai/study-plan/today',
  QUESTIONS_LIST: '/questions',
  QUESTIONS_ADAPTIVE: '/questions/adaptive',
  QUESTIONS_PRACTICE: '/questions/practice',
  TESTS_LIST: '/tests',
  TESTS_GENERATE: '/tests/generate/full-length',
  STUDY_PLANS_TODAY: '/study-plans/today',
  STUDY_PLANS_STATS: '/study-plans/stats',
  STUDY_SESSIONS_START: '/study-plans/sessions/start',
  ANALYTICS_PERFORMANCE: '/analytics/performance',
  ANALYTICS_SUBJECTS: '/analytics/subjects',
  ANALYTICS_FORECAST: '/analytics/forecast',
  FLASHCARDS: '/flashcards',
  REVISION_DUE: '/revision/due',
  LEADERBOARD_NATIONAL: '/leaderboard/national',
  LEADERBOARD_MY_RANK: '/leaderboard/my-rank',
  GAMIFICATION_PROFILE: '/gamification/profile',
  GAMIFICATION_ACHIEVEMENTS: '/gamification/achievements',
  PAYMENTS_PLANS: '/payments/plans',
  PAYMENTS_CREATE_ORDER: '/payments/create-order',
  PAYMENTS_VERIFY: '/payments/verify',
  NOTIFICATIONS: { LIST: '/notifications', REGISTER_TOKEN: '/notifications/register-token', UNREAD_COUNT: '/notifications/unread-count' },
  SUBJECTS_LIST: '/subjects',
} as const;
